{{- $serviceName := include "name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-{{ .Values.azureVoteBack.service.name }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.azureVoteBack.service.type }}
  ports:
    - port: {{ .Values.azureVoteBack.service.externalPort }}
      name: mysql
  selector:
    app: {{ include "name" . }}
    component: {{ $serviceName }}-{{ .Values.azureVoteBack.deployment.name }}
    release: {{ .Release.Name }}
